### ISSUE TITLE
Unable to add google account to device

### ISSUE THREAD

**Issue by sjdrc** [crDroidMod/android_vendor_gapps#2]
I'm running on a Pixel 2 XL on the latest release of 9.0 - PQ2A.190405.003, along with android-prepare-vendor (which is google device specific, using the --full flag for compatibility with gapps). I performed the following steps:

* Cloned your repository into vendor/gapps
* Added ```$(call inherit-product, vendor/gapps/config.mk)``` to the end of ```device/google/taimen/device.mk```
* Ran a full build from there and everything built successfully
* Flashed my phone and booted up, all apps appear to be installed
* Opened Settings > Accounts > Add Account > Google
* A screen pops up saying "Checking Info..."
* App goes black and all I can do is exit

Have you encountered any errors like this or do you have any ideas on what I can do from here? Thanks for your help.

**Comment by 1582130940** [comment]
Check the permissions of the Google service framework and Google services, perhaps the permissions issue
